[build]
  functions = "functions/"
  publish = "dist/"
  command = "export ELM_HOME=\"elm-stuff\" && npm install && npm run build"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["elm-stuff"]

[dev]
  command = "npm start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"
